version: '2.1'



services:

  redis-master:
    image: redis:3.2.5-alpine
    container_name: redis-master
    volumes:
      - "./.data:/data"
    network_mode: bridge
    # ports:
    #   - "6379:6379"
    build:
      context: .
      labels:
        SERVICE_6379_NAME: "redis-master"
        SERVICE_6379_CHECK_TCP: "true"
        SERVICE_6379_CHECK_INTERVAL: "30s"
        SERVICE_6379_CHECK_TIMEOUT: "3s"


  redis-slave:
    image: redis:3.2.5-alpine
    network_mode: bridge
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./.data:/data"

  # Instance 1
  sentinel1:
    network_mode: bridge
    build:
      context: ./redis-sentinel

  # Instance 2
  sentinel2:
    network_mode: bridge
    build:
      context: ./redis-sentinel

  # Instance 3
  sentinel3:
    network_mode: bridge
    build:
      context: ./redis-sentinel

  gremlins:
    image: qualimente/gremlins
    depends_on:
      - redis-master
    volumes:
      - ./gremlins/profiles:/app/gremlins/profiles
    command: gremlins -m gremlins.profiles.redis_faults -p redis_faults.profile
    network_mode: "service:redis-master"
    pid: host
    cap_add:
      - NET_ADMIN
